[package]
name = "datafusion_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion =  { version = "37.0.0" }
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }